name: Example

on: push

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print helo
        run: echo "hello world"

  build_skim:
    runs-on: ubuntu-latest
    container: rootproject/root:${{ matrix.version }}
    strategy:
      matrix:
	version: ["6.26.10-conda", "latest"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - run: |
          COMPILER=$(root-config --cxx)
          FLAGS=$(root-config --cflags --libs)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS









# TO USE THE LATEST VERSION OF UBUNTU/ROOT
#  build_skim_latest:
#    runs-on: ubuntu-latest
#    container: rootproject/root:latest
#    steps:
#      - name: Check out repo
#        uses: actions/checkout@v4
#      - run: |
#          COMPILER=$(root-config --cxx)
#          FLAGS=$(root-config --cflags --libs)
#          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS




# GETTING ROOT WITH CONDA  
#  build_skim_conda:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash -el {0}
#    steps:
#      - name: checkout repository
#        uses: actions/checkout@v4
#      - name: Install ROOT
#        uses: mamba-org/setup-micromamba@v1
#        with:
#          environment-name: env
#          create-args: root
#      - name: build
#        run: |
#          COMPILER=$(root-config --cxx)
#          FLAGS=$(root-config --cflags --libs)
#          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS
